### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vadim9999** [atherdon/markdown-to-email#137]
![image](https://user-images.githubusercontent.com/35640573/98438868-ca6ab800-20f5-11eb-9491-f26890862c35.png)

**Comment by coder-do** [comment]
✔✔✔
@atherdon  мы эти ошибки исправили уже , мы с помощью тестов нашли и исправили )

**Comment by atherdon** [comment]
@coder-do спасибо. тогда закрываю
