### ISSUE TITLE
[react] include resolver for path aliases

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#179]
https://www.youtube.com/watch?v=WpzhUi3a7fc&ab_channel=LevelUpTuts

@master-bogdan here is a small improvement that we can do later

**Comment by master-bogdan** [comment]
@atherdon I founded this cool thing in native NextJS
https://nextjs.org/docs/advanced-features/module-path-aliases
I will integrate it in this pull request

**Comment by atherdon** [comment]
good - thanks, then i'm closing it
