### ISSUE TITLE
testing full template generator

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#180]
1. Title is old https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/progressing/flatfile5/full-generated-template.html#L20

2. old path to main logo(my fault): https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/progressing/flatfile5/full-generated-template.html#L570

3. I can't find preview text

4. h1 has br inside https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/progressing/flatfile5/full-generated-template.html#L760

5.  and content was not wrapped into table https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/progressing/flatfile5/full-generated-template.html#L786-L866

6. *** was replaced like it's bold, plus do we have a tag to make some text centered?

**Comment by atherdon** [comment]
full link: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/progressing/flatfile5/full-generated-template.html

**Comment by vadim9999** [comment]
@atherdon All links are broken. I can't understand what I should do in this task

**Comment by atherdon** [comment]
@vadim9999 sorry, my fault

here it is: https://github.com/atherdon/newsletters/blob/master/archive/Thematic/2020/%20December/completed/flatfile5/full-generated-template.html

**Comment by vadim9999** [comment]
@atherdon should we close this?

**Comment by atherdon** [comment]
yep, closing it
