### ISSUE TITLE
[react] small tasks

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#190]
- template/first - нужно ли нам сделать HOC, чтобы проще выглядела структура в first? просто когда мы будем тестировать все - нам таким образом будет проще.
- стоит ли нам например скачать базовый html для vouchful и разбить его на какие то части, или уже дождемся Вадима?
- template/content-only - предлагаю заполнить его. его отличие от first/full в одном - нету logotop, logobottom и нету sponsors
- нужно ли нам попробывать поставить remark и для отдельной страницы посмотреть как он выведет нам markdown?

@master-bogdan

**Comment by master-bogdan** [comment]
@atherdon 
1.если все типично, да можем визуально сделать обвертку HOC, со структурой боди, хедер, футер, я правильно понял?
2. можем попробовать, в любом случае оно даст базу компонентов
3. ок
4. тут имеется в виду сгенерить ХТМЛ страницу некстом и пропустить ее через ремарк?

**Comment by atherdon** [comment]
@master-bogdan вроде да, но мне сложно так ответить - хочу посмотреть :) просто это будет наш основной темплейт, пока мы не перейдем на другие - и потратить на него еще немного времени выглядит хорошей инвестицией.  как должно выглядеть - просто меньше строчек кода в одном файле :)

2. да и мне интересно - сильно ли это изменит наш процесс. это конечно задача не сильно срочная - можно вначале сделать чтото другое.

4. я имею ввиду попробывать https://github.com/atherdon/markdown-to-email/issues/171 или https://github.com/atherdon/markdown-to-email/issues/142 и просто закинуть внутрь этой функции например такой код и посмотреть как он будет выглядеть в output 

код:
```
It's very easy to make some words **bold** and 
other words *italic* with Markdown. 
You can even [link to Google!](http://google.com)
```

**Comment by master-bogdan** [comment]
@atherdon 
3 пункт. Там есть рабочий вариант
`
<div id="__next"><p>It&#x27;s very easy to make some words <strong>bold</strong> and
other words <em>italic</em> with Markdown.
You can even <a href="http://google.com">link to Google!</a></p></div>
`
Помимо скриптов некста, в теле генерит вот такую вот штуку

**Comment by master-bogdan** [comment]
@atherdon 
1.добавил HOC
3.Сделал страницу контент онли
Я думаю можно закрывать и вынести vouchfill в отдельный issues

**Comment by atherdon** [comment]
> @atherdon
> 4 пункт. Там есть рабочий вариант
> Помимо скриптов некста, в теле генерит вот такую вот штуку
> `<div id="__next"><p>It&#x27;s very easy to make some words <strong>bold</strong> and other words <em>italic</em> with Markdown. You can even <a href="http://google.com">link to Google!</a></p></div>`

единственное что меня смущает - сможет ли он оборачивать в компоненты, которые мненужно.
тоесть табличную верстку то мы добавим, но вот например сможет ли он добавлять инлайн стили к ссылкам и делать wrapper для каждого параграфа - еще является для меня загадкой

**Comment by atherdon** [comment]
могу закрыть этот таск, а обсуждение по remark и маркдауну вынести в отдельный таск

**Comment by master-bogdan** [comment]
@atherdon да, я думаю можно закрывать
