### ISSUE TITLE
[Main branch]

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#225]
> * Changed a little bit logic using bind and call on test.
> * Added warnings when source or source-full.md contains images
> 
> ![image](https://user-images.githubusercontent.com/35640573/102690407-46d4d880-4216-11eb-9122-d55afbf39f3d.png)
> 
> * Added errors and not generating full template when full-surce.md doesn't have two sponsors blocks and preview Text
> 
> NOTE: if we remove first sponsorship block it will display that source-full.md doesn't has sponsorhipBottom
> ![image](https://user-images.githubusercontent.com/35640573/102690590-8223d700-4217-11eb-9455-145105cd5fd0.png)
> 
> * this is bug but not important for now. the main idea is that source-full.md must have two sponsorship blocks
> 
> ![image](https://user-images.githubusercontent.com/35640573/102690601-91a32000-4217-11eb-9b90-d15837e70927.png)

based on https://github.com/atherdon/markdown-to-email/pull/224

**Comment by master-bogdan** [comment]
@atherdon 
if in helpers this method looks like this
![2020-12-27_00-20](https://user-images.githubusercontent.com/63278323/103160071-6b621f00-47d9-11eb-8a12-bebe509d6798.png)
 
it parse this
![2020-12-27_00-20_1](https://user-images.githubusercontent.com/63278323/103160078-85036680-47d9-11eb-80a7-630f0ed1cdd9.png)

But if I add some module
![2](https://user-images.githubusercontent.com/63278323/103160094-a3696200-47d9-11eb-97cf-df7dff80d40c.png)

It will be render this
![3](https://user-images.githubusercontent.com/63278323/103160107-cbf15c00-47d9-11eb-9c3b-3190331e9a41.png)

And if I just pass some string like `const Heading =\ `<h1>Hello WORLD</h1>\`` it will be render this

**Comment by atherdon** [comment]
@master-bogdan then it's not working ideally as we want it :) 
And it's is fine.

I'll propose to start upgrading that method - `replaceHTMLWrapper`
split it into few parts, try to debug it and find a place where it's crashing.

Plus, feel free to replace that ugly loop with loop from lodash module
