### ISSUE TITLE
[react] babel

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#242]
should we have this?
```
"plugins": [
    [
      "babel-plugin-transform-react-jsx",
      {
        "ignore": [
          "**/*.test.js",
          "**/*.test.jsx",
          "styles.js"
        ]
      }
    ]
```

**Comment by master-bogdan** [comment]
@atherdon this is ne thinks which come with new react, I think we need wait some time before using this

**Comment by atherdon** [comment]
my goal was to generate HTML from react components that we have. and then open both raw HTML and generated react page and compare code on my monitor. and if this plugin will help me to do it - we can try

**Comment by master-bogdan** [comment]
@atherdon from description

> Upgrading to the new transform is completely optional, but it has a few benefits:

With the new transform, you can use JSX without importing React.
Depending on your setup, its compiled output may slightly improve the bundle size.
It will enable future improvements that reduce the number of concepts you need to learn React.
