### ISSUE TITLE
[react] console errors  [resolved]

### ISSUE THREAD

**Issue by coder-do** [atherdon/markdown-to-email#243]
Запускаю тесты выпадают такие ошибки:  

![Code_SMixFIvh4q](https://user-images.githubusercontent.com/68124376/102996407-895f2380-453c-11eb-82a6-947a7b9f72e5.png)
![Code_UBe4vl8c5T](https://user-images.githubusercontent.com/68124376/102996408-8a905080-453c-11eb-9e1f-6ba217a71f64.png)
![Code_Xm8F49bdko](https://user-images.githubusercontent.com/68124376/102996410-8a905080-453c-11eb-99f9-3e0cb293b6c2.png)
![Code_yLkR9NCH9D](https://user-images.githubusercontent.com/68124376/102996411-8b28e700-453c-11eb-9a09-139453cd93fd.png)
![Code_ypfEcVtLfL](https://user-images.githubusercontent.com/68124376/102996412-8b28e700-453c-11eb-9ba8-40a1caca30f8.png)

**Comment by master-bogdan** [comment]
@coder-do удалось пофиксить?

**Comment by coder-do** [comment]
> @coder-do удалось пофиксить?

@master-bogdan  да уже пофиксил это
