### ISSUE TITLE
code-refactoring

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#287]
что вы думаете насчет мелких функций, которые хранятся в файле parser.js
если они используются один раз - может их вынести в utils? чтобы этот файл был покороче

вынести можно:
- https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js#L95
- https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js#L72
- https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js#L62
- https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js#L47
- https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js#L32

@coder-do задачка на потом.

**Comment by coder-do** [comment]
код рефакторинг то что мы должны были вынести в`utils.js` Oleh8978  полностью очистил эти функции из файла в его вчерашнем пулле  ((

**Comment by atherdon** [comment]
@coder-do доконца не понимаю проблему. этих функций больше нет? или непонятно на какой строчке смотреть?

**Comment by atherdon** [comment]
если что - вот пулл вчрашний https://github.com/atherdon/markdown-to-email/pull/288/files

**Comment by coder-do** [comment]
https://github.com/atherdon/markdown-to-email/blob/master/src/parser.js
неиспользуемые функции имею ввиду  функции:  checker,   link_searcher,  contnet_rewriter,  link_cleaner    мы эти должны были вынести в `utils.js`

**Comment by atherdon** [comment]
@Oleh8978 а нам нужны эти функции?

**Comment by atherdon** [comment]
@coder-do давайте пока вынесем мелкие функции которые остались, а там дальше видно будет

**Comment by Oleh8978** [comment]
Нет они больше не нужны, эти функции удаляли линки после апдейта все работает и они не нужны

**Comment by atherdon** [comment]
гуд @Oleh8978 спасибо

**Comment by coder-do** [comment]
✔✔✔
