### ISSUE TITLE
work with sub-modules

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#324]
т.к я не знал как решить проблему с данным генератором и закончить работу над первой версией - я пытался атаковать проблему с разных сторон.

Один из вариантов - разбить проект на несколько частей. Каждая часть должна выполнять только одну задачу. Это упростит  работу над новыми фичами а также могло ускорить процесс.
я не закончил работу надо под-модулями и переключился на проект с админкой.
сейчас у нас есть время и возможность закончить эту часть. Подмодули помогут над начать переход от версии 1, к версии 2 - в которой у нас есть реакт компоненты.

подмодули лежат в папке package.
1) подмодуль, который должен в себе хранить папку [layouts](https://github.com/atherdon/markdown-to-email/tree/master/layouts). нужно сравнить версии файлов - потому что мы могли чтото изменить.
находится в https://github.com/atherdon/markdown-to-email/tree/master/package/layouts
каждый раз, когда мы добавим новые изменения - мне прийдется делать пуш кода на npm. только потом мы сможем установить новую версию внутри ветки main.

2) подмодуль, который должен хранить внутри себя все regex константы. тк эта часть очень статическая - ее вообще нет смысла хранить внутри основного проекта. плюс, вынос в отдельный модуль поможет нам разделить тесты на 2 части. часть тестов, которая проверяет парсинг и тесты на результаты внутри функций. находится внутри https://github.com/atherdon/markdown-to-email/tree/main/package/newsletter-constants/newsletter-constants

3) подмодуль, который копирует логику layouts, но внутри себя несет не plain HTML внутри js файлов, а реакт компоненты.
c помощью этого модуля - я хочу проверить одну гипотезу: сможет ли генератор конвертировать markdown в реакт, без всяких ошибок или нет? находится в https://github.com/atherdon/markdown-to-email/tree/main/package/generator-react-components

нашей задачей будет:
-  сделать так, чтобы подмодули работали.
- потом удалить дублирующийся код из основного проекта
- подключить в основной код данные из подмодулей
- проверить и пофиксить ошибки.
- после этого мы сможем подумать о том, что нужно сделать в версии 2.0

**Comment by atherdon** [comment]
cc @kolserdav можем на следующей неделе обсудить эта задачу

**Comment by kolserdav** [comment]
Первое, что бросилось в глаза, по пункту 2, что парсят HTML при помощи regex, это на ноде, лучше делать через  либу window, которая позволит работать с DOM как в браузере. Заставлять работать regex, зная что существует window это испытание, может быть переделать на window? Это намного снизит вероятность ошибок парсинга, и упростит получение нужных элементов и операции над ними.

**Comment by kolserdav** [comment]
> сможет ли генератор конвертировать markdown в реакт, без всяких ошибок или нет?
>
Да, просто вместо HTML создавать react элементы.

**Comment by kolserdav** [comment]
>

    сделать так, чтобы подмодули работали.
    потом удалить дублирующийся код из основного проекта
    подключить в основной код данные из подмодулей
    проверить и пофиксить ошибки.
    после этого мы сможем подумать о том, что нужно сделать в версии 2.0
>
 Что именно не работает?

**Comment by atherdon** [comment]
> > сможет ли генератор конвертировать markdown в реакт, без всяких ошибок или нет?
> 
> По идее да. Вот что нашел:
> https://www.npmjs.com/package/markdown-to-jsx
> https://www.npmjs.com/package/html-to-react

Я смотрел markdown to jsx - нопочему то мы сильно не продвинулись дальше. можем попробывать это во второй версии. потому что теперь, когда нам не нужен html - много всего упрощается.
а тк markdown очень часто используется в statis website generator - эта задача уже давно была решена более умными девами. плюс там есть еще передача переменных. но нужно смотреть и тестировать.

**Comment by atherdon** [comment]
> > 
> 
> ```
> сделать так, чтобы подмодули работали.
> потом удалить дублирующийся код из основного проекта
> подключить в основной код данные из подмодулей
> проверить и пофиксить ошибки.
> после этого мы сможем подумать о том, что нужно сделать в версии 2.0
> ```
> 
> > 
> 
> Что именно не работает?

помойму я тестировал только layouts подмодуль. обычно проблемой был формат return данных.
тоесть мы собираем package с помощью rollup - и в итоге мы получаем большой объект, в котором есть поля с нашим html.

в main ветке были установлена старая версия модуля - вы можете ее подключить в каком то файле - вытащить или весь объект или его части и посмотреть как там внутри все содержится
@kolserdav

**Comment by kolserdav** [comment]
Там половина в разобранном состоянии, проще будет по описанию задачи определить что делать. Как я понял и чего-то собирать объект для подключения в другом месте?

**Comment by atherdon** [comment]
да, давайте считать что все недоделано - потому что нужно проверять все сначала. все правильно вы поняли. главное что нужно - доделать, потом я делаю npm publish и потом мы уже сможем подключать модули в основном проекте.

основная идея была в том, чтобы вынести части в подмодули - потом почистить код внутри src от этих массивов и начать двигаться в сторону реакт ветки

**Comment by atherdon** [comment]
Проще всего нам будет начать с layouts и довести этот модуль до конца.
таким образом мы прогоним и процесс с public модуля и обновления его в src.

**Comment by atherdon** [comment]
поидее готово
