### ISSUE TITLE
layouts submodule as separate task

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#326]
Я думаю что нам нужно начать с этого подмодуля как с первой задачи. это поможет стартауть этот проект.

Основная задача этого подмодуля является в том, чтобы убрать нашу папку layouts из кода генератора
![image](https://user-images.githubusercontent.com/1469198/110259946-d470ca80-7fb2-11eb-981d-62c8688ab7e8.png)
а также упростить нашу логику подключения темплейтов внутри папки /src
т.к. файлы внутри папки layouts статические - нет смысла просто хранить их так как сейчас.
тем более что в версии 2 мы заменим plain HTML на реакт компоненты. 

А значит что потом эта папка все равно удалится. но т.к. сейчас нам нужно чтобы генератор все же работал - нам нужно сделать так - чтобы обе версии: plain HTML и react components - смогли работать одновременно некоторое время.

тоесть генератор должен только "генерировать" большой файл, но при этом не знать, что именно в него отправляют.

это также позволить улучшить структуру кода и избавится от таких методов как

- https://github.com/atherdon/markdown-to-email/blob/main/src/utils.js#L6
- https://github.com/atherdon/markdown-to-email/blob/main/src/helpers.js#L3

Модуль сделан на rollup. Работает он просто, когда уже готов конфиг. единственная проблема - его неудобно дебажить.

код лежит тут: https://github.com/atherdon/markdown-to-email/blob/main/package/layouts

для проверки на ошибки я использую https://github.com/atherdon/markdown-to-email/blob/main/package/layouts/package.json#L12
для сборки уже в финальные файлы https://github.com/atherdon/markdown-to-email/blob/main/package/layouts/package.json#L11

возможно мне нужно будет сделать npm org и заинвайтить и вас в нее - чтобы вы сами могли делать publish и сразу проверять подключения модуля внутри src

**Comment by atherdon** [comment]
если зареганы на npm - дайте почту и я попробую добавить вас в орг

**Comment by atherdon** [comment]
ссылки на модули
- https://www.npmjs.com/package/atherdon-newsletter-react/
- https://www.npmjs.com/package/atherdon-newsletter-constants
- https://www.npmjs.com/package/atherdon-newsletter-js-layouts
cc @kolserdav

**Comment by kolserdav** [comment]
Сначала, как я понял нужно с layouts разобраться. Чтобы убрать её вообще из репозитория, а переместить в библиотеку "atherdon-newsletter-js-layouts" и переподключить в репозитории, а также переписать способ храния HTML шаблонов, чтобы они хранились не в строках js файлов, а с расширением .html для удобства отладки. Считаем, что актуальными являются шаблоны, которые в репозитории, а не в библиотеке.  
По скриптам там только два работающих скрипта `parse` и `parse:full`. Надеюсь с этим правильно понял?


Единственное, я не в курсе, получается раз rollup-ом собирает layouts в бандл значит где-то этот бандл подключается с помощью <script src="bundle.js"></script> чтобы использовать шаблоны на html странице, или зачем в один файл собитает?

**Comment by kolserdav** [comment]
Если перепишем на html надо будет в либе сообразить какой нибудь микро шаблонизатор который будет делать автомодстановку таких моментов:
```html
<title>The Secrets of High-Performing DevOps teams</title>
${headStyles}
<!--[if !mso]><!-->
${fonts}
<!--<![endif]-->
</head>`;
```

**Comment by atherdon** [comment]
в один файл собирает - чтобы мне было проще потом html из этого файла вставлять в сисему, через которую мы шлем emails

**Comment by atherdon** [comment]
другой цели там нету

**Comment by atherdon** [comment]
плюс, я решил не использовать шаблонизаторы - потому что за 10 лет ничего лучше не придумали. тоесть шаблонизаторы влегкую проигрывают тому же реакту

**Comment by kolserdav** [comment]
Дучше этот https://www.npmjs.com/package/@rollup/plugin-html

**Comment by kolserdav** [comment]
> плюс, я решил не использовать шаблонизаторы - потому что за 10 лет ничего лучше не придумали. тоесть шаблонизаторы влегкую проигрывают тому же реакту
>
У реакта свой шаблонизатор наверное. Я к тому что если на html переписать, то и собирать надо будет подругому, старый конфиг сборки уже не пойдет.

**Comment by kolserdav** [comment]
или я что-то не так понял?

**Comment by atherdon** [comment]
> Дучше этот https://www.npmjs.com/package/@rollup/plugin-html

нужно посмотреть



> У реакта свой шаблонизатор наверное. Я к тому что если на html переписать, то и собирать надо будет подругому, старый конфиг сборки уже не пойдет.

да, конечно. я имею ввиду стандартные шаблонизаторы\template-engine логика которых мне напоминает php. я про всякие pug/jade/mustashe и т.д.

вы все правильно поняли, просто внутри этого генератора много мелких ньюансов.
Мы сейчас делаем несколько шагов - конвертируя одно в другое и т.д. на каждом шаге появлялись ошибки, которые мы исправляем. и круто что мы наконецто дошли до финального результата.

но скорее всего - при переходе на версию 2 - когда появятся реакт компоненты и т.д. - нам скорее всего получится пропустить несколько шагов - которые мы делаем в этой версии. Т.е. скорее всего конвертация из маркдауна будет возможно сразу генерировать HTML - без всяких посредников

**Comment by atherdon** [comment]
поидее готово, закрываю таск
