### ISSUE TITLE
[constants] feedback

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#356]
we have similar content at https://github.com/atherdon/markdown-to-email/blob/main/package/newsletter-constants/src/index.js & https://github.com/atherdon/markdown-to-email/blob/main/package/newsletter-constants/src/constants.js

i wanna use a separate file, maybe even few, in order to separate default markdown tags, and our custom stuff

**Comment by vadim9999** [comment]
16b448cc61b7715efccbfb44a0c7c41630ba11cd
