### ISSUE TITLE
setup eslint & prettier for submodules

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#359]
step 0 - just install it

https://github.com/atherdon/markdown-to-email/tree/main/package

cc @coder-do

**Comment by atherdon** [comment]
@coder-do can you help, please

**Comment by atherdon** [comment]
https://github.com/atherdon/markdown-to-email/pull/371#pullrequestreview-640684149

**Comment by coder-do** [comment]
это всё - в 3 папках установил уже

**Comment by atherdon** [comment]
сс @vadim9999
