### ISSUE TITLE
Find out what to do with other callbacks

### ISSUE THREAD

**Issue by vadim9999** [atherdon/markdown-to-email#370]
Now in submodule generator react components we doesn't have wrappers for this tags:

- [x] q
- [x]  del
- [x] code
- [x] blockquote

**Comment by atherdon** [comment]
can we do placeholders for now?
in order to make it looks like it work.
like `<Del></Del>` `<Q></Q>` can it be a quick solution?

**Comment by vadim9999** [comment]
I think yes, then I will add Del and Q and other like Blackquote into the react submodule and connect it into main module
