### ISSUE TITLE
обновить ссылки на картинки внутри футера на соц медиа

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#375]
Начать с этой ветки: https://github.com/atherdon/markdown-to-email/tree/wworking-version

ссылка на ссылки: https://github.com/atherdon/newsletters/issues/320#issuecomment-825000315

меняем для этого блока
![image](https://user-images.githubusercontent.com/1469198/115765805-e1554c00-a3af-11eb-88fb-fcac8a7c31b1.png)

**Comment by atherdon** [comment]
сс @coder-do

**Comment by atherdon** [comment]
потом поменяем и в main ветке и в реакт ветке

**Comment by atherdon** [comment]
https://github.com/atherdon/markdown-to-email/blob/main/package/layouts/src/full-template.js#L580

**Comment by coder-do** [comment]
@atherdon 
по моему и в футере тоже надо менять кроме фул-темплейта
https://github.com/atherdon/markdown-to-email/blob/2a242836c2da7ca8b739daed499d3891af770b98/package/layouts/src/body/footer.js#L251

**Comment by atherdon** [comment]
@coder-do да

**Comment by atherdon** [comment]
мне кажется что реакт ветка вообще не имеет компонент для футера с социальными ссылками.
как минимум я их там не нашел

**Comment by coder-do** [comment]
я в реакт ветке искал - вот что нашёл:
https://github.com/atherdon/markdown-to-email/blob/997e2e0f77542344044c3ddf7eec22f5c54c56be/frontend-next/templates/content-only/Footer/Footer.js#L43

https://github.com/atherdon/markdown-to-email/blob/997e2e0f77542344044c3ddf7eec22f5c54c56be/frontend-next/templates/first/Footer/Footer.js#L43

**Comment by coder-do** [comment]
А вот в ветке main в папке generator-react-components этих ссылок не было )

**Comment by atherdon** [comment]
ок, значит пока меняем в реакт ветке вначале

>

**Comment by atherdon** [comment]
генератор-react-comp пока не вижу смысла трогать. потом с ним разберемся
