### ISSUE TITLE
[react] install basic packages 

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#386]
similar to https://github.com/atherdon/subscribe-form/issues/78

for 
- https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero/package/content
- https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero/package/typography
- https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero/package/vouchful
cc @coder-do

**Comment by atherdon** [comment]
if you have time, we can do this task @coder-do

**Comment by coder-do** [comment]
я просто не уверен что на этой задаче ничего не сломаю в коде (

**Comment by atherdon** [comment]
ничего, если вы чтото сломаете - тогда вам прийдется это исправлять. все ок
- это просто базовый setup

>

**Comment by coder-do** [comment]
как здесь настроен так и сделаю в этих 3 папках тоже https://github.com/atherdon/markdown-to-email/tree/main/package/layouts
потом если что поправим

Плюс эта ссылка недействительна https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero/package/typography
возможно вы имели ввиду https://github.com/atherdon/markdown-to-email/tree/react-components-stage-zero/package/components/typography
@atherdon

**Comment by atherdon** [comment]
ну я наверное поменял папку
