### ISSUE TITLE
Bug when generating full react template

### ISSUE THREAD

**Issue by vadim9999** [atherdon/markdown-to-email#393]
`npm run parseReact:full`

When generating full react template Strong tag is broken.

![image](https://user-images.githubusercontent.com/35640573/116287038-97e27380-a798-11eb-97dc-196e8a0f6eb4.png)

![image](https://user-images.githubusercontent.com/35640573/116287130-b8123280-a798-11eb-9f1f-8e53dc39a1c5.png)

**Comment by vadim9999** [comment]
@atherdon what is it and is it valid case?
![image](https://user-images.githubusercontent.com/35640573/116289025-c2cdc700-a79a-11eb-97aa-32918d840afa.png)

**Comment by atherdon** [comment]
i think someone was trying to test how RegEx for many stars `***` works. There wouldn't be such a case,
but we have `***` as separator.

**Comment by vadim9999** [comment]
it will be another task for it
I am closing this issue
