### ISSUE TITLE
not sure if it's used or not

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#460]
https://github.com/atherdon/markdown-to-email/blob/wworking-version/layouts/body/logoBottom.js#L74

**Comment by coder-do** [comment]
@atherdon   я заметил что он импортируется но не используется
https://github.com/atherdon/markdown-to-email/blob/aab9d32b62506a194a6b97a44aa0ea5bfb25a3ca/layouts/body.js#L5

**Comment by atherdon** [comment]
да, странно конечно. хорошо что не используется. наверное мы просто начнем
аккуратно менять layouts

>
