### ISSUE TITLE
how to fix some tests in main branch

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#482]
xxx

**Comment by atherdon** [comment]
@coder-do финальный шаг в этом таске: объединение 2х импортов в один: https://github.com/atherdon/markdown-to-email/blob/main/src/tests/typography/images-only/index.test.js#L5-L6

**Comment by atherdon** [comment]
я заметил что в некоторых тестах все равно идет импорт callbacks со старых файлов
![Uploading image.png…]()

**Comment by atherdon** [comment]
![atherdon-markdown-to-email-main](https://user-images.githubusercontent.com/1469198/119814538-30345b00-bef3-11eb-9944-12287d60abc5.png)

**Comment by coder-do** [comment]
да я знаю - я только в типографии менял - обьединю импорты и перейду в другие папки тоже и поетапно фиксить буду тесты

**Comment by atherdon** [comment]
отлично

**Comment by atherdon** [comment]
done
