### ISSUE TITLE
callbacks package issues

### ISSUE THREAD

**Issue by coder-do** [atherdon/markdown-to-email#504]
@atherdon 

Я заметил в пакете колбеков есть некоторые упущенные моменты:

- Из `helpers.js` в `index.js` из 5 экспортированных функций импортируется только 1 - это `replaceMarkdown` 

файл `helpers.js`
```js 
export {  newLine,
  replaceMarkdown,  replaceMarkdownPreviewText,
  replaceReactWrapper,  replaceHTMLWrapper,};
```

`index.js`
https://github.com/atherdon/markdown-to-email/blob/1e325cdd24d6ec6da2f048c7484fb58c13516ae5/package/callbacks/src/index.js#L5

- Нужно все вместе сделать экспорт из файла индекса и сделать npm publish
- В тестах нужны эти функции и изза того что нету в пекедже , тесты проваливаются

**Comment by atherdon** [comment]
выглядит логично, а можете показать где используются методы, такие как ```
replaceMarkdownPreviewText,
  replaceReactWrapper,  replaceHTMLWrapper
```

если скинете ссылки с code-lines будет круто.
и да, согласен с тем что нужно сделать доп экспорты - можете сделать их в этом файле а я потом выложу новую версию пакета на npm

**Comment by coder-do** [comment]
да найду - кроме всего этого - самы выжный экспорт это `newline`  он почти везде есть в тестах

**Comment by coder-do** [comment]
> если скинете ссылки с code-lines будет круто.


Here `newline`
https://github.com/atherdon/markdown-to-email/blob/68aff79be5d61e8c4f06763c976f8abad89876a0/src/tests/methods/callback-simple.test.js#L5

`replaceHTMLWrapper`
https://github.com/atherdon/markdown-to-email/blob/68aff79be5d61e8c4f06763c976f8abad89876a0/src/tests/methods/helpers.test.js#L1

`replaceMarkdownPreviewText`
https://github.com/atherdon/markdown-to-email/blob/68aff79be5d61e8c4f06763c976f8abad89876a0/src/tests/methods/parse1.test.js#L15

@atherdon

**Comment by atherdon** [comment]
ok, делайте экспорт в package а я его потом выложу сегодня обновленный

>

**Comment by atherdon** [comment]
думаю готово или будет готово скоро
