### ISSUE TITLE
video transcribe

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#510]
0. Нам нужно ускорится 
Потому что я думал что мы будем заканчивать генератор а получается что мы его только поправляем. и это отдалят перенос. возможно просто изза того что код нестабильный - мы и не можем перейти на версию2.

---

или мы делаем улучшения в ветке main - нужно проверить как работает генератор full и react.
или мы должны сделать 5-7 темлпейтов руками, чтобы они на мне не висели.

---

branding email - today

сделайте версию без adv block, только аккуратно, чтобы старая хрень еще больше не покрешилась.

добавьте warning чтобы когда контент не работает - это было видно вwarnings, а не мы лезли в html и смотрели.

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/120186870-c1217400-c21c-11eb-8144-239187abaa1a.mp4

**Comment by coder-do** [comment]
> или мы должны сделать 5-7 темлпейтов руками, чтобы они на мне не висели.

Сделаю руками и пулл - потом посмотрим как будет темплейт

**Comment by atherdon** [comment]
ok

>

**Comment by atherdon** [comment]
> добавьте warning чтобы когда контент не работает - это было видно вwarnings, а не мы лезли в html и смотрели.

не думаю что это готово @code

**Comment by atherdon** [comment]
cc @coder-do

**Comment by coder-do** [comment]
@atherdon  вроде бы это всё да ?

**Comment by coder-do** [comment]
@atherdon 
думаю всё - вроде другого ничего не упустил я с видео

**Comment by atherdon** [comment]
закрываю, но если вы сможете записать видео о том как работает генератор без advertising - это мне поможет - потому что я неделю в код нормально не смотрел

**Comment by coder-do** [comment]
я там ничего особенного не делал здесь опишу:
https://github.com/atherdon/markdown-to-email/blob/0d076462f996289051314675fac93b2640508d97/package.json#L8
описал скрипт, где переменной PARSE присвоил noAdv чтобы потом проверить в файле парсе

https://github.com/atherdon/markdown-to-email/blob/0d076462f996289051314675fac93b2640508d97/src/parse.js#L47
а здесь в иф я проверяю типо если парсе без адвертайзинга идет - пропусткай - в противном случае будет парсить спонсорский контент

Пока что так подумал - если в процессе работы этого скрипта буду кое какие косяки - поправим

@atherdon
