### ISSUE TITLE
full-template update

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#514]
https://user-images.githubusercontent.com/1469198/120469916-a16c8600-c3ab-11eb-9843-0f5d30893bc7.mp4

**Comment by atherdon** [comment]
сделали ли мы отдельную команду, для генерирования темлейта без advertising? @coder-do

**Comment by coder-do** [comment]
> сделали ли мы отдельную команду, для генерирования темлейта без advertising?

я в wworking-version пробовал парсить контент без advertising (ну без лого спонсора и рядом сним текста)
и парсился норм, просто я думаю если наш существующий скрипт парсит и то , и то - зачем новый скрипт нам?
просто я не понимаю как это делать - поэтому с другой стороны посмотрел на проблему ))

**Comment by coder-do** [comment]
@atherdon 
я вроде протестировал как парсит скрипт без адв - вроде норм сработал
можете и вы посмотрите если что и закончим этот таск

**Comment by atherdon** [comment]
предлагаю пока просто закрыть и гуд
