### ISSUE TITLE
replace with new path

### ISSUE THREAD

**Issue by atherdon** [atherdon/markdown-to-email#515]
[тут я добавил видео](https://github.com/atherdon/newsletters/issues/381#issuecomment-853309227) о том как заливать картинки в s3

но я думаю что лого HN уже валялось там.
тк s3 bucket это копия [этого репозитория](https://gitlab.com/hackernoon/creative/-/tree/master/newsletters/logos), посмотрите где там валялось лого хакернуна и найдите его в бакете уже.

**Comment by atherdon** [comment]
поискав в наших ветках, я понял что везде мы так и ссылаемся на старый путь к лого. ну теперь мы это изменим.
как тут например: https://github.com/atherdon/markdown-to-email/blob/4d1f26f754faa3951271c9a7e9c286fceca9668f/components/body/logo/Logo.js#L27

**Comment by atherdon** [comment]
а в full-template файле мы изменили пути? я протос неуверен что видел

**Comment by coder-do** [comment]
сделал
